name: laravelencrypt
recipe: lamp
config:
  via: "cli"
  php: "8.2"

services:
  php81:
    type: php:8.1
    via: "cli"


tooling:
  cleanup:
    cmd: rm -rf vendor composer.lock

  setup81:
    service: php81
    cmd: rm -rf vendor composer.lock && composer install



  setup82:
    service: appserver
    cmd: rm -rf vendor composer.lock && composer install

  test82:
    service: appserver
    cmd: composer phpunit
  test81:
    service: php81
    cmd: composer phpunit


  stan82:
    service: appserver
    cmd: composer phpstan
  stan81:
    service: php81
    cmd: composer phpstan

  all82:
    service: appserver
    cmd:
      - rm -rf vendor composer.lock && composer install
      - composer phpunit
      - composer phpstan

  all81:
    service: php81
    cmd:
      - rm -rf vendor composer.lock && composer install
      - composer phpunit
      - composer phpstan


