plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/gitlab"
  - - "semantic-release-slack-bot"
    - notifyOnSuccess: true
      notifyOnFail: false
      markdownReleaseNotes: true
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
branches:
  - "master"
  - "main"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "beta"
    prerelease: true
