<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up()
    {
        Schema::create('keystore_role_{{role}}', function (Blueprint $table) {
             $table->id();
             $table->foreignId('rsa_key_id')->unique()->references('id')->on('rsa_keys')->onDelete('CASCADE')->onUpdate('RESTRICT');
             $table->text('key');
             $table->timestamps();
        });
    }

}
